var localization={
	head: {
		title: "[Create] JARN - online handwriting text redactor",
	},
	body: {
		step_1_header: "st step: photo uploading",
		file_text: "Upload original image",
		file_text_2: "Upload jarn file",
		file_text_3: "Upload the dictionary",
		backwards_to_index: "<span class='arrows'><<</span> To index",
		to_2: "2nd step &gt;&gt;",
		step_2_header: "nd step: processing your image",
		panel_header: "Controle panel<span class='show_sign'<span class='arrows'>>></span>></span>",
		option_1_header: "Colour blur:",
		option_2_header: "Image size:",
		option_3_header: "Selection box size:",
		option_4_header: "Image movements:",
		option_5_header: "Selection box colour:",
		option_6_header: "Controle panel opacity:",
		lang_choose_title: "Choose text's language:",
		ud_lang_text: "Upload the file",
		backwards_to_1: "<span class='arrows'><<</span> Choose another file",
		forwards_to_3: "3rd step &gt;&gt;",
		step_3_header: "rd step: file downloading",
		backwards_to_2: "<span class='arrows'><<</span> 2nd step",
		forwards_to_download: "Download my handwriting file &gt;&gt;",
		tmp_canvas_move: '&times;&nbsp; Move',
		tmp_canvas_pencil: '&#9679; Pencil',
		tmp_canvas_eraser: '&#9632; Eraser',
		congratulations: "Congratulations, You've just created your jarn-file! Download it and go to the text editor.<br/>(3rd page on the index page)",
	},
	msgs: {
		other_file: {
			title: "Choose another file?",
			text: "Do you really want to choose another file? All changes won't be saved.",
		},
		too_big_image: {
			title: "Image is too big",
			text: "Warning! Image's size is grater than 1000*1000 px. During your work your computer may reload, turn off or hang up. In that case you will lose all your unsaved files. By pressing \"OK\" You will continue at your own risk.",
		},
		choose_language: {
			title: "Choose the language",
			text: "Use the panel on the right side to select the text's language",
		},
		wrong_file_type: {
			title: "Wrong type of the file",
			text: "Only plain text is supported.",
		},
		list_of_letters: {
			title: "You didn't enter all the letters from the list. Are you sure want to continue? The full list of unused letters:",
			text: "Are you sure want to continue?",
		},
		transfer_confirm: {
			title: "Confirm the transfer",
			text: "Go to the index page?",
		},
		settings: {
			title: "Settings",
			text_1: "Language",
			text_2: "I want to see JARN in: ",
			text_3: "Hints",
			text_4: "Show hints",
		},
		ok_button: "OK",
		cancel_button: "Cancel",
	},
	hints: {
		hint_hide: "P.S. You can disable hints in global settings menu on the top of the site.",
		settings: "Show global settings.",
		file: "Upload an image with handwriting text on it.",
		to_2: "You should upload an image at first.",
		canvas: "By using your mouse show the colour of handwriting text (just click on the text by your crosshair). Slide the mouse on the left to open a control panel.",
		option_1: "The higher value shows darker colours. Use this leave only text, taken away odd things (like lines, cells, red margins, etc).",
		option_2: "Allows zooming your image.",
		option_3: "Enables image transition mode.",
		option_4: "Allows you choose a selection box colour.",
		lang_choose: "Choose the text's language.",
		ud_lang_file: "Select your own dictionary, unless your text's language is presented in the list. You can read about creating dictionaries in \"Instruction\" chapter in global settings menu.",
		lang_panel: "Here will be shown all the letters, that you have entered by a selection box.",
		canvas_sub_aside: "You can draw or erase a part of a letter by pencil and eraser.",
		letter_canvas: "Previewing your ready jarn-file. This file contains your handwriting. Text editor requires him.",
		selection_box_size: "Changing this setting will delete all the letters, that you have entered before!",
	},
};